# To set the application display name, only define either `app.name` or `app.name_byte_array`.
# For a rule of thumb:
# * Use `app.name` if your app name doesn't contain any non-ANSI characters.
# * Otherwise, convert your app name to UTF-8 byte array, comma delimited, and put
#   it in `app.name_byte_array`
app.name=Love2Droid
app.application_id=top.wsdx233.love2droid
app.orientation=unspecified
app.version_code=1
app.version_name=0.1.0

# No need to modify anything past this line!
android.enableJetifier=false
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true
android.dependency.useConstraints=true
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.workers.max=2
org.gradle.parallel=false
